### ISSUE TITLE
opBNB chain (w/o traces)

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/archive-registry#100]
Public RPC: 

https://opbnb-mainnet-rpc.bnbchain.org

**Comment by belopash** [comment]
@octo-gone why is it blocked?

**Comment by dzhelezov** [comment]
https://chainlist.org/?chain=245022926&testnets=true&search=opbnb

**Comment by octo-gone** [comment]
All endpoints for the time of blocking were unavailable or broken. Will try starting again
