### ISSUE TITLE
Boba Networks

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/archive-registry#102]
Use the endpoints we use for FireSquid:

- Boba Mainnet
- Boba Testnet
- Boba Moonbeam
- Boba BNB
- Boba BNB Testnet
- Boba AVAX

Take the endpoints from: https://chainlist.org/?chain=245022926&testnets=true&search=Boba
If there issues, go to the TG chat: Subsquid <> Boba

**Comment by octo-gone** [comment]
We can sync all of them without traces, otherwise we need to find RPC providers

**Comment by dzhelezov** [comment]
UPD:
Let's support only the networks: Boba-ETH, Boba-Avalanche, Boba-BSC
