### ISSUE TITLE
Missing networks for archives

### ISSUE THREAD

**Issue by uiii** [subsquid/archive-registry#27]
Hello, I've found there are some archives in `archives.json` file but no networks with the same name in `networks.json`.

Archives with these network names have no matching network in `networks.json`:

- `phala`
- `shibuya`
- `social-parachain`

I've also found there are some networks which has no listed archives but the url with the network name works:

- `kilt`: https://kilt.explorer.subsquid.io/graphql 
- `mangata-x`: https://mangata-x.explorer.subsquid.io/graphql
- `subsocial`: https://subsocial.explorer.subsquid.io/graphql

Is this intended?

**Comment by octo-gone** [comment]
Hello, and thank you for the issue! 

File `networks.json` used for describing networks. We will fix and add `phala` and `shibuya` to it. `subsocial` network is named as `subsocial-parachain` insize `netoworks.json`.

Soon we will add `kilt` and `mangata-x` networks, but the endpoints are working already. However they are not tested, verified or synced yet.

**Comment by uiii** [comment]
Good, thanks. 

Why is the `subsocial` named `subsocial-parachain` in networks? Will you change it, or leave for backward compatibility?
