### ISSUE TITLE
Support Aleph Zero Mainnet

### ISSUE THREAD

**Issue by wottpal** [subsquid/archive-registry#30]

**Comment by octo-gone** [comment]
Hey! We already have support of Aleph Zero Mainnet in plans, I will notify and close the issue when it will be ready. If you'd like more information or if you want to participate and provide archive for this network, please write a comment or update a description. Thank you!

**Comment by octo-gone** [comment]
Aleph Zero added [26d2cd9](https://github.com/subsquid/archive-registry/commit/26d2cd941a2598944833600f5d11c536ec1068b3)
