### ISSUE TITLE
Zora

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/archive-registry#65]
RPC (public, probably slow and rate-limited):

https://rpc.zora.energy

**Comment by octo-gone** [comment]
Endpoint returns 404

**Comment by dzhelezov** [comment]
Hmm check https://chainlist.org/?chain=245022926&testnets=true&search=zora

**Comment by octo-gone** [comment]
This is the only one, even in chainlist

**Comment by dzhelezov** [comment]
Can you check again? Works for me now
