### ISSUE TITLE
ArrowSquid Substrate

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/archive-registry#99]
1) Check the sheet and make sure all networks supported by FireSquid are included. Do not include networks for which we have RPC issues
2) Double-check the ingesters supported by Dwellir operate normally (dump and ingest)
3) Setup ingest with public RPC for networks supported by FireSquid

**Comment by octo-gone** [comment]
Archive | Dwellir | Issues | Added
---|:---:|---|:---:
aleph-zero-testnet | | |
altair | | |
bajun | | |
bifrost | ✔ | |
bifrost-polkadot | | |
bitcountry-pioneer | | |
calamari | | |
centrifuge | | |
cere | | |
clover | ✔ | |
collectives | | |
composable-finance | | |
crust | | |
elysium | | |
elysium-testnet | | |
enjin-matrix | | |
equilibrium | | |
foucoco | | |
frequency-testnet | | |
gear-testnet | | |
gmordie | | |
hashed | | |
heiko | | |
integritee-network | ✔ | |
invarch-tinkernet |  | |
joystream | | |
kabocha | | |
kylin | | |
manta | | |
moonsama | | |
myriad | | |
myriad-testnet | | |
origin-trail | ✔ | |
pangolin | | |
pangoro | | |
parallel | ✔ | |
peaq | | |
pendulum | | |
picasso | | |
polkadex | ✔ | |
reef | | |
reef-testnet | | |
robonomics | | |
sora | | |
sora-testnet | | |
statemine | | |
statemint | | |
subsocial-parachain | | |
subsocial | | |
t0rn | | |
tanganika | | |
ternoa | | |
tidechain | | |
vara | | |
westend-collectives | | |
xx-network | | |
